import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import bundleAnalyzer from "@next/bundle-analyzer";
import { withPayload } from "@payloadcms/next/withPayload";
import type { NextConfig } from "next";

const dirname = path.dirname(fileURLToPath(import.meta.url));
const withBundleAnalyzer = bundleAnalyzer({ enabled: process.env.ANALYZE === "true" });

// 301s from the old WordPress URLs, generated by `npm run wp:import`.
type Redirect = { source: string; destination: string; permanent: boolean };
const legacyRedirects = JSON.parse(readFileSync(path.join(dirname, "src/redirects.json"), "utf8")) as Redirect[];

const nextConfig: NextConfig = {
  poweredByHeader: false,
  reactStrictMode: true,
  experimental: {
    // Inline CSS off: Next inlines it twice (a <style> in the HTML and again
    // in the RSC payload, ~19 KB gzip per page). An external file is sent
    // once and cached across pages; Lighthouse LCP measured the same.
    inlineCss: false,
  },
  images: {
    formats: ["image/avif", "image/webp"],
    // 40/55: full-bleed hero photos (phone/desktop), mostly under the mist.
    qualities: [40, 55, 75],
    minimumCacheTTL: 60 * 60 * 24 * 30,
    // Local uploads (dev/CI) are served by Payload; production uses Vercel Blob.
    localPatterns: [{ pathname: "/api/midia/file/**" }],
    remotePatterns: [{ protocol: "https", hostname: "*.public.blob.vercel-storage.com" }],
  },
  turbopack: { root: path.resolve(dirname) },
  async redirects() {
    return legacyRedirects;
  },
  async headers() {
    return [
      {
        source: "/:path*",
        headers: [
          { key: "X-Content-Type-Options", value: "nosniff" },
          { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
          { key: "X-Frame-Options", value: "SAMEORIGIN" },
          { key: "Permissions-Policy", value: "camera=(), microphone=(), geolocation=()" },
        ],
      },
    ];
  },
};

export default withPayload(withBundleAnalyzer(nextConfig), { devBundleServerPackages: false });
