/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    usuarios: UsuarioAuthOperations;
  };
  blocks: {};
  collections: {
    noticias: Noticia;
    projetos: Projeto;
    publicacoes: Publicacoe;
    paginas: Pagina;
    videos: Video;
    categorias: Categoria;
    parceiros: Parceiro;
    pessoas: Pessoa;
    midia: Midia;
    documentos: Documento;
    usuarios: Usuario;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    noticias: NoticiasSelect<false> | NoticiasSelect<true>;
    projetos: ProjetosSelect<false> | ProjetosSelect<true>;
    publicacoes: PublicacoesSelect<false> | PublicacoesSelect<true>;
    paginas: PaginasSelect<false> | PaginasSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    categorias: CategoriasSelect<false> | CategoriasSelect<true>;
    parceiros: ParceirosSelect<false> | ParceirosSelect<true>;
    pessoas: PessoasSelect<false> | PessoasSelect<true>;
    midia: MidiaSelect<false> | MidiaSelect<true>;
    documentos: DocumentosSelect<false> | DocumentosSelect<true>;
    usuarios: UsuariosSelect<false> | UsuariosSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    site: Site;
    numeros: Numero;
    timeline: Timeline;
  };
  globalsSelect: {
    site: SiteSelect<false> | SiteSelect<true>;
    numeros: NumerosSelect<false> | NumerosSelect<true>;
    timeline: TimelineSelect<false> | TimelineSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Usuario;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UsuarioAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noticias".
 */
export interface Noticia {
  id: number;
  titulo: string;
  /**
   * Uma ou duas frases. Aparece nas listas e no Google.
   */
  resumo?: string | null;
  capa?: (number | null) | Midia;
  conteudo: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Gerado a partir do título se ficar em branco. Mudar o slug de algo já publicado quebra links.
   */
  slug: string;
  publicadoEm: string;
  categorias?: (number | Categoria)[] | null;
  projetos?: (number | Projeto)[] | null;
  /**
   * Opcional. Se vazio, usamos o título, o resumo e a capa.
   */
  seo?: {
    titulo?: string | null;
    descricao?: string | null;
    imagem?: (number | null) | Midia;
  };
  /**
   * Preenchido pela migração do WordPress.
   */
  legado?: {
    wpId?: number | null;
    wpUrl?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Fotos em alta, até 15 MB. O site gera versões leves (AVIF/WebP) automaticamente.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "midia".
 */
export interface Midia {
  id: number;
  /**
   * Descreva a imagem para quem não pode vê-la. Ex.: “Agricultora colhendo pinhão em Painel”.
   */
  alt: string;
  /**
   * Marcado pela migração quando a imagem veio sem descrição. Some ao editar o texto.
   */
  altProvisorio?: boolean | null;
  legenda?: string | null;
  credito?: string | null;
  origem?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    miniatura?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    cartao?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    destaque?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias".
 */
export interface Categoria {
  id: number;
  titulo: string;
  /**
   * Gerado a partir do título se ficar em branco. Mudar o slug de algo já publicado quebra links.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projetos".
 */
export interface Projeto {
  id: number;
  titulo: string;
  resumo?: string | null;
  capa?: (number | null) | Midia;
  conteudo?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  galeria?:
    | {
        imagem: number | Midia;
        id?: string | null;
      }[]
    | null;
  /**
   * Gerado a partir do título se ficar em branco. Mudar o slug de algo já publicado quebra links.
   */
  slug: string;
  /**
   * Uso interno por enquanto: a situação não aparece no site.
   */
  situacao: 'ativo' | 'concluido';
  areas?: ('educacao-popular' | 'agroecologia' | 'restauracao-florestal' | 'cultura-sat-pinhao')[] | null;
  inicio?: string | null;
  fim?: string | null;
  financiadores?: (number | Parceiro)[] | null;
  destaque?: boolean | null;
  /**
   * Opcional. Se vazio, usamos o título, o resumo e a capa.
   */
  seo?: {
    titulo?: string | null;
    descricao?: string | null;
    imagem?: (number | null) | Midia;
  };
  /**
   * Preenchido pela migração do WordPress.
   */
  legado?: {
    wpId?: number | null;
    wpUrl?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parceiros".
 */
export interface Parceiro {
  id: number;
  nome: string;
  descricao?: string | null;
  tipo: 'apoiador' | 'parceiro';
  /**
   * De preferência SVG ou PNG com fundo transparente.
   */
  logo?: (number | null) | Midia;
  site?: string | null;
  ordem?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publicacoes".
 */
export interface Publicacoe {
  id: number;
  titulo: string;
  descricao?: string | null;
  /**
   * Autores ou instituição.
   */
  autoria?: string | null;
  capa?: (number | null) | Midia;
  arquivo?: (number | null) | Documento;
  /**
   * Use quando o arquivo está hospedado em outro site.
   */
  linkExterno?: string | null;
  /**
   * Gerado a partir do título se ficar em branco. Mudar o slug de algo já publicado quebra links.
   */
  slug: string;
  ano?: number | null;
  /**
   * Preenchido pela migração do WordPress.
   */
  legado?: {
    wpId?: number | null;
    wpUrl?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documentos".
 */
export interface Documento {
  id: number;
  titulo: string;
  origem?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Páginas avulsas, como as do mini-site do Projeto Restaurar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paginas".
 */
export interface Pagina {
  id: number;
  titulo: string;
  conteudo?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Sem barra inicial. Ex.: projetos/projeto-restaurar/galeria-de-especies
   */
  caminho: string;
  projeto?: (number | null) | Projeto;
  /**
   * Preenchido pela migração do WordPress.
   */
  legado?: {
    wpId?: number | null;
    wpUrl?: string | null;
  };
  /**
   * Opcional. Se vazio, usamos o título, o resumo e a capa.
   */
  seo?: {
    titulo?: string | null;
    descricao?: string | null;
    imagem?: (number | null) | Midia;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Os vídeos do canal também são lidos automaticamente; cadastre aqui os que quer destacar ou legendar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  titulo: string;
  youtube: string;
  descricao?: string | null;
  publicadoEm?: string | null;
  destaque?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pessoas".
 */
export interface Pessoa {
  id: number;
  nome: string;
  grupo: 'diretoria' | 'conselho-fiscal' | 'equipe-tecnica';
  /**
   * Ex.: Presidente, Coordenador de projetos.
   */
  cargo?: string | null;
  formacao?: string | null;
  foto?: (number | null) | Midia;
  email?: string | null;
  /**
   * Desmarcado por padrão para evitar spam.
   */
  emailPublico?: boolean | null;
  ordem?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usuarios".
 */
export interface Usuario {
  id: number;
  nome: string;
  roles: ('admin' | 'editor')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'usuarios';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'noticias';
        value: number | Noticia;
      } | null)
    | ({
        relationTo: 'projetos';
        value: number | Projeto;
      } | null)
    | ({
        relationTo: 'publicacoes';
        value: number | Publicacoe;
      } | null)
    | ({
        relationTo: 'paginas';
        value: number | Pagina;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null)
    | ({
        relationTo: 'categorias';
        value: number | Categoria;
      } | null)
    | ({
        relationTo: 'parceiros';
        value: number | Parceiro;
      } | null)
    | ({
        relationTo: 'pessoas';
        value: number | Pessoa;
      } | null)
    | ({
        relationTo: 'midia';
        value: number | Midia;
      } | null)
    | ({
        relationTo: 'documentos';
        value: number | Documento;
      } | null)
    | ({
        relationTo: 'usuarios';
        value: number | Usuario;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'usuarios';
    value: number | Usuario;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'usuarios';
    value: number | Usuario;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noticias_select".
 */
export interface NoticiasSelect<T extends boolean = true> {
  titulo?: T;
  resumo?: T;
  capa?: T;
  conteudo?: T;
  slug?: T;
  publicadoEm?: T;
  categorias?: T;
  projetos?: T;
  seo?:
    | T
    | {
        titulo?: T;
        descricao?: T;
        imagem?: T;
      };
  legado?:
    | T
    | {
        wpId?: T;
        wpUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projetos_select".
 */
export interface ProjetosSelect<T extends boolean = true> {
  titulo?: T;
  resumo?: T;
  capa?: T;
  conteudo?: T;
  galeria?:
    | T
    | {
        imagem?: T;
        id?: T;
      };
  slug?: T;
  situacao?: T;
  areas?: T;
  inicio?: T;
  fim?: T;
  financiadores?: T;
  destaque?: T;
  seo?:
    | T
    | {
        titulo?: T;
        descricao?: T;
        imagem?: T;
      };
  legado?:
    | T
    | {
        wpId?: T;
        wpUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publicacoes_select".
 */
export interface PublicacoesSelect<T extends boolean = true> {
  titulo?: T;
  descricao?: T;
  autoria?: T;
  capa?: T;
  arquivo?: T;
  linkExterno?: T;
  slug?: T;
  ano?: T;
  legado?:
    | T
    | {
        wpId?: T;
        wpUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paginas_select".
 */
export interface PaginasSelect<T extends boolean = true> {
  titulo?: T;
  conteudo?: T;
  caminho?: T;
  projeto?: T;
  legado?:
    | T
    | {
        wpId?: T;
        wpUrl?: T;
      };
  seo?:
    | T
    | {
        titulo?: T;
        descricao?: T;
        imagem?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  titulo?: T;
  youtube?: T;
  descricao?: T;
  publicadoEm?: T;
  destaque?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias_select".
 */
export interface CategoriasSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parceiros_select".
 */
export interface ParceirosSelect<T extends boolean = true> {
  nome?: T;
  descricao?: T;
  tipo?: T;
  logo?: T;
  site?: T;
  ordem?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pessoas_select".
 */
export interface PessoasSelect<T extends boolean = true> {
  nome?: T;
  grupo?: T;
  cargo?: T;
  formacao?: T;
  foto?: T;
  email?: T;
  emailPublico?: T;
  ordem?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "midia_select".
 */
export interface MidiaSelect<T extends boolean = true> {
  alt?: T;
  altProvisorio?: T;
  legenda?: T;
  credito?: T;
  origem?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        miniatura?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        cartao?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        destaque?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documentos_select".
 */
export interface DocumentosSelect<T extends boolean = true> {
  titulo?: T;
  origem?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usuarios_select".
 */
export interface UsuariosSelect<T extends boolean = true> {
  nome?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site".
 */
export interface Site {
  id: number;
  nome: string;
  razaoSocial?: string | null;
  cnpj?: string | null;
  email: string;
  telefone?: string | null;
  endereco?: {
    logradouro?: string | null;
    cidade?: string | null;
    uf?: string | null;
    cep?: string | null;
  };
  redes?: {
    instagram?: string | null;
    facebook?: string | null;
    youtube?: string | null;
    /**
     * Usado para listar os vídeos automaticamente (sem chave de API).
     */
    youtubeChannelId?: string | null;
  };
  estatuto?: (number | null) | Documento;
  /**
   * Ex.: 08/02/2026 a 07/02/2029
   */
  mandatoDiretoria?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Contadores animados da home. Use apenas números confirmados.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "numeros".
 */
export interface Numero {
  id: number;
  itens?:
    | {
        valor: number;
        /**
         * Ex.: +
         */
        prefixo?: string | null;
        /**
         * Ex.: ha, anos
         */
        sufixo?: string | null;
        rotulo: string;
        /**
         * De onde vem o número (uso interno).
         */
        fonte?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Marcos de 1983 até hoje, exibidos na home e em Quem somos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeline".
 */
export interface Timeline {
  id: number;
  marcos?:
    | {
        ano: number;
        titulo: string;
        texto?: string | null;
        imagem?: (number | null) | Midia;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_select".
 */
export interface SiteSelect<T extends boolean = true> {
  nome?: T;
  razaoSocial?: T;
  cnpj?: T;
  email?: T;
  telefone?: T;
  endereco?:
    | T
    | {
        logradouro?: T;
        cidade?: T;
        uf?: T;
        cep?: T;
      };
  redes?:
    | T
    | {
        instagram?: T;
        facebook?: T;
        youtube?: T;
        youtubeChannelId?: T;
      };
  estatuto?: T;
  mandatoDiretoria?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "numeros_select".
 */
export interface NumerosSelect<T extends boolean = true> {
  itens?:
    | T
    | {
        valor?: T;
        prefixo?: T;
        sufixo?: T;
        rotulo?: T;
        fonte?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeline_select".
 */
export interface TimelineSelect<T extends boolean = true> {
  marcos?:
    | T
    | {
        ano?: T;
        titulo?: T;
        texto?: T;
        imagem?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}